"""Generate the frontier-LLM robustness deliverables from committed results:
  - paper/tables/tab_llm.tex          (comparison table on the 300-item subset)
  - paper/autonums_llm.tex            (\\newcommands: exact model ids, invalid rates,
                                        and the \\llmrobustnessparagraph prose)
All numbers come from results/analysis_subset.json + results/llm_models.json, plus the
GPT-5.6 duplicate-response counts from results/llm_raw__gpt56.jsonl.
"""
import os, json, collections

HERE = os.path.dirname(__file__)
RESULTS = os.path.join(HERE, "..", "results")
PAPER = os.path.join(HERE, "..", "paper")

# tag -> display + macro-id name; LLM tags expected: gpt56, sonnet5, gemini
DISP = {"minilm-l6 (subset)": "MiniLM-L6", "mdeberta-base (subset)": "mDeBERTa-base",
        "xlmr-large (subset)": "XLM-R-large", "gpt56": "GPT-5.6",
        "sonnet5": "Claude Sonnet 5", "gemini": "Gemini 3.1 Pro"}
ORDER = ["minilm-l6 (subset)", "mdeberta-base (subset)", "xlmr-large (subset)",
         "gpt56", "sonnet5", "gemini"]


def p(x, d=1):
    return f"{100*x:.{d}f}" if x == x else "--"


def main():
    A = json.load(open(os.path.join(RESULTS, "analysis_subset.json")))
    models = A["models"]
    mids = json.load(open(os.path.join(RESULTS, "llm_models.json"))) \
        if os.path.exists(os.path.join(RESULTS, "llm_models.json")) else {}

    # ---- comparison table ----
    rows = [r"\begin{tabular}{lrrrrrr}", r"\toprule",
            r"Model & Acc. & Agree & Unan. & $\kappa$ & Flip & Neg.\ RR \\", r"\midrule"]
    present = [t for t in ORDER if t in models]
    last_ow = None
    for t in present:
        if t.endswith("(subset)"):
            last_ow = t
    for t in present:
        r = models[t]
        rr = r["phenomena"]["negation"]["risk_ratio"]
        rows.append(f"{DISP.get(t,t)} & {p(r['mean_per_lang_acc'])} & {p(r['mean_pairwise_agreement'])} & "
                    f"{p(r['unanimity'])} & {r['fleiss_kappa']:.2f} & {p(r['flip_rate(non_unanimous)'])} & "
                    f"{rr:.2f} \\\\")
        if t == last_ow:
            rows.append(r"\midrule")
    rows += [r"\bottomrule", r"\end{tabular}"]
    open(os.path.join(PAPER, "tables", "tab_llm.tex"), "w", encoding="utf-8", newline="\n").write("\n".join(rows) + "\n")

    # ---- macros + paragraph ----
    lines = ["% AUTO-GENERATED by make_llm.py"]

    def mac(name, val):
        lines.append(f"\\newcommand{{\\{name}}}{{{val}\\xspace}}")

    idname = {"gpt56": "GptModelId", "sonnet5": "SonnetModelId", "gemini": "GeminiModelId"}
    invname = {"gpt56": "GptInvalid", "sonnet5": "SonnetInvalid", "gemini": "GeminiInvalid"}
    for tag in ["gpt56", "sonnet5", "gemini"]:
        if tag in mids:
            mac(idname[tag], mids[tag]["model"].replace("_", "\\_"))
            mac(invname[tag], p(mids[tag]["invalid_frac"], 2) + "\\%")

    # GPT-5.6 instances with more than one successful response in the raw file (scoring uses
    # the first in file order; see llm_eval.load_cache). Counted from the raw responses.
    raw_path = os.path.join(RESULTS, "llm_raw__gpt56.jsonl")
    if os.path.exists(raw_path):
        from llm_eval import _ok, parse_label
        succ = collections.defaultdict(list)
        for line in open(raw_path, encoding="utf-8"):
            try:
                r = json.loads(line)
            except Exception:
                continue
            if _ok(r):
                succ[(r["idx"], r["lang"])].append(parse_label(r["output"]))
        dup = [v for v in succ.values() if len(v) > 1]
        if dup and max(len(v) for v in dup) != 2:
            raise SystemExit("expected at most two successful responses per GPT-5.6 instance")
        mac("GptDupInstances", f"{len(dup):,}".replace(",", "{,}"))
        mac("GptDupConflicting", f"{sum(len(set(v)) > 1 for v in dup):,}".replace(",", "{,}"))

    # compose the robustness paragraph from the actual numbers.
    def g(t, k):
        return models[t][k] if t in models else float("nan")

    def acc(t):
        return p(g(t, "mean_per_lang_acc"))

    def flip(t):
        return p(g(t, "flip_rate(non_unanimous)"))

    def unan(t):
        return p(g(t, "unanimity"))

    def kap(t):
        return f"{g(t, 'fleiss_kappa'):.2f}"

    ow = "mdeberta-base (subset)"
    order = [("gpt56", "GPT-5.6"), ("sonnet5", "Claude Sonnet~5"), ("gemini", "Gemini 3.1 Pro")]
    present = [(t, n) for t, n in order if t in models]
    # max cue chi2 across all subset models (reported as a statistical-power caveat)
    max_chi = 0.0
    for t in models:
        for c in ("negation", "modality", "quantifier"):
            max_chi = max(max_chi, models[t]["phenomena"][c]["chi2_yates"])
    per = "; ".join(f"{n} {acc(t)}\\%/{flip(t)}\\%/{unan(t)}\\%/{kap(t)}" for t, n in present)
    para = (
        "On the fixed \\NumSubset{}-item subset, all three frontier LLMs reproduce the central "
        "effect (Table~\\ref{tab:llm}): despite high per-language accuracy, they return a "
        "unanimous answer across the 15 languages for well under half of the problems and flip "
        "on a majority or near-majority, with only moderate chance-corrected agreement "
        "(accuracy / flip / unanimity / $\\kappa$: " + per + "). The open-weight models on the "
        f"same 300 items behave comparably (mDeBERTa {flip(ow)}\\% flips), so the "
        "accuracy-hidden item-level instability is not an artifact of the smaller open-weight "
        "checkpoints; it persists for frontier reasoning LLMs. The 300-item subset is, "
        "however, underpowered for the source-cue analysis: no cue (negation, modality, "
        f"quantifier) reaches significance for any model here (all Yates $\\chi^2<{max_chi:.1f}"
        "<3.84$), including the open-weight models whose full-set negation effect is highly "
        "significant (\\S\\ref{sec:pervasive}). The subset therefore neither confirms nor "
        "refutes the (non-)concentration pattern for the LLMs; we treat the LLM study strictly "
        "as corroboration of the headline instability and base all cue-level and primary claims "
        "on the full open-weight test set.")
    lines.append(f"\\newcommand{{\\llmrobustnessparagraph}}{{{para}}}")

    open(os.path.join(PAPER, "autonums_llm.tex"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("wrote paper/tables/tab_llm.tex and paper/autonums_llm.tex")


if __name__ == "__main__":
    main()
