"""Emit paper/autonums.tex: every numeric claim in the paper as a \\newcommand read
from results/analysis__{split}.json. The manuscript \\input's this file and uses only
these macros for numbers -> no hand-transcription, full traceability.
"""
import os, json, argparse

HERE = os.path.dirname(__file__)
RESULTS = os.path.join(HERE, "..", "results")
PAPER = os.path.join(HERE, "..", "paper")

PREFIX = {"minilm-l6": "Minilm", "mdeberta-base": "Mdeberta", "xlmr-large": "Xlmr"}


def pct(x, d=1):
    return f"{100*x:.{d}f}"


def num(x, d=2):
    return f"{x:.{d}f}"


def emit(lines, name, val):
    lines.append(f"\\newcommand{{\\{name}}}{{{val}\\xspace}}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--splits", nargs="+", default=["test", "dev"])
    args = ap.parse_args()

    lines = ["% AUTO-GENERATED by make_macros.py. Do not edit by hand.",
             "\\usepackage{xspace}"]
    emit(lines, "NumLangs", "15")
    subpath = os.path.join(RESULTS, "llm_subset.json")
    if os.path.exists(subpath):
        sub = json.load(open(subpath))
        emit(lines, "NumSubset", str(sub["n"]))
        emit(lines, "Seed", str(sub["seed"]))
    for split in args.splits:
        path = os.path.join(RESULTS, f"analysis__{split}.json")
        if not os.path.exists(path):
            continue
        A = json.load(open(path))
        S = "" if split == "test" else "Dev"
        emit(lines, f"NumItems{S if S else 'Test'}", f"{A['n_items']:,}".replace(",", "{,}"))
        for k, v in A["cue_counts"].items():
            emit(lines, f"CueCount{k.capitalize()}{S}", f"{v:,}".replace(",", "{,}"))
        for tag, r in A["models"].items():
            P = PREFIX.get(tag, tag.replace("-", "")) + S
            emit(lines, f"{P}Acc", pct(r["mean_per_lang_acc"]))
            emit(lines, f"{P}Flip", pct(r["flip_rate(non_unanimous)"]))
            emit(lines, f"{P}Unan", pct(r["unanimity"]))
            emit(lines, f"{P}Agree", pct(r["mean_pairwise_agreement"]))
            emit(lines, f"{P}Kappa", num(r["fleiss_kappa"]))
            emit(lines, f"{P}UnanWrong", pct(r["decomp"]["unanimous_wrong"]))
            emit(lines, f"{P}Split", pct(r["decomp"]["split"]))
            emit(lines, f"{P}MajCorrectOnSplit", pct(r["maj_correct_on_split"]))
            emit(lines, f"{P}MinConfHi", pct(r["confidence"]["frac_minority_preds_high_conf(>0.9)"]))
            emit(lines, f"{P}CorrResource", num(r["corr_flipinvolve_resource"]))
            emit(lines, f"{P}CorrAcc", num(r["corr_flipinvolve_accuracy"]))
            # min/max per-language accuracy spread (for "high accuracy" claim)
            accs = r["per_lang_acc"]
            hi = max(accs, key=accs.get); lo = min(accs, key=accs.get)
            emit(lines, f"{P}AccMax", pct(accs[hi])); emit(lines, f"{P}AccMaxLang", hi)
            emit(lines, f"{P}AccMin", pct(accs[lo])); emit(lines, f"{P}AccMinLang", lo)
            for key, short in [("negation", "Neg"), ("modality", "Mod"), ("quantifier", "Quant"), ("any", "Any")]:
                p = r["phenomena"][key]
                emit(lines, f"{P}{short}RR", num(p["risk_ratio"]))
                emit(lines, f"{P}{short}Cued", pct(p["flip_cued"]))
                emit(lines, f"{P}{short}Uncued", pct(p["flip_uncued"]))
                emit(lines, f"{P}{short}Chi", f"{p['chi2_yates']:.1f}")

    out = os.path.join(PAPER, "autonums.tex")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out} with {len(lines)-2} macros")


if __name__ == "__main__":
    main()
